### ISSUE TITLE
Appcrash

### ISSUE THREAD

**Issue by filson1** [TheSorm/RetSim#13]
When starting the desktop application, it'll crash during loading.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	RetSimDesktop.exe
  Application Version:	1.2.1.0
  Application Timestamp:	6195442d
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.24384
  Fault Module Timestamp:	5c6e248c
  Exception Code:	e0434352
  Exception Offset:	000000000000be0d
  OS Version:	6.1.7601.2.1.0.256.48

Tried in a clean VM with same OS (win7) and WebView2 runtime installed. .Net runtime 4.7.2.
Initially issues with api-ms-win-core-winrt-l1-1-0.dll missing, but sorted by dumping a copy from a realtek driver into the install dir.

Source tree mentions a non-desktop version, but would need a little more info on how to get that working, in case the above isn't solvable.

**Comment by filson1** [comment]
Took the liberty of cloning and building the solution with an updated .net 6.0.201 x64 sdk on VS Code.
Solution builds a debug binary for the RetSimDesktop and dll for RetSim.
App loads and then crashes with same exception code. On first attempt, the UI was loaded just before crash.

Event viewer shows the exception as:
Application: RetSimDesktop.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller2.set_DefaultBackgroundColor(COREWEBVIEW2_COLOR backgroundColor)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_DefaultBackgroundColor(Color value)
   at Microsoft.Web.WebView2.Wpf.WebView2.DefaultBackgroundColorPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Microsoft.Web.WebView2.Wpf.WebView2.set_DefaultBackgroundColor(Color value)
   at RetSimDesktop.WoWTooltip.InitializeAsync() in C:\Users\Tasos\Programming\Visual Studio\RetSim\cs\RetSim\RetSimDesktop\View\WoWTooltip.xaml.cs:line 60
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at RetSimDesktop.App.Main()

**Comment by tasosgretsistas** [comment]
Sorry for the late response - this looks like a version issue with WebView. Are you sure you got the x64 version of Webview2?
